=== Kloapte/the-dnd-pub-data/schemas/core-rules/v1/language.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:thedndpub:schemas:core-rules:language:v1",
  "title": "Language",
  "allOf": [
    {
      "$ref": "urn:thedndpub:schemas:core-rules:common:v1#/$defs/identity"
    }
  ],
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "name",
    "sourceMetadata"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^language:[a-z0-9]+(?:-[a-z0-9]+)*:[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "sourceMetadata": {
      "$ref": "urn:thedndpub:schemas:core-rules:common:v1#/$defs/sourceMetadata"
    },
    "category": {
      "enum": [
        "standard",
        "exotic",
        "rare",
        "secret"
      ]
    },
    "script": {
      "type": "string",
      "minLength": 1
    },
    "origin": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "urn:thedndpub:schemas:core-rules:common:v1#/$defs/reference"
      }
    },
    "typicalSpeakers": {
      "type": "array",
      "minItems": 1,
      "items": {
        "oneOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "targetType",
              "id"
            ],
            "properties": {
              "targetType": {
                "const": "creature"
              },
              "id": {
                "type": "string",
                "pattern": "^creature:[a-z0-9-]+:[a-z0-9-]+$"
              }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "filter"
            ],
            "properties": {
              "filter": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "targetType",
                  "creatureTypes"
                ],
                "properties": {
                  "targetType": {
                    "const": "creature"
                  },
                  "creatureTypes": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                      "enum": [
                        "aberration",
                        "beast",
                        "celestial",
                        "construct",
                        "dragon",
                        "elemental",
                        "fey",
                        "fiend",
                        "giant",
                        "humanoid",
                        "monstrosity",
                        "ooze",
                        "plant",
                        "undead"
                      ]
                    }
                  },
                  "tags": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "required": [
                        "group",
                        "value"
                      ],
                      "properties": {
                        "group": {
                          "type": "string",
                          "minLength": 1
                        },
                        "value": {
                          "type": "string",
                          "minLength": 1
                        }
                      }
                    }
                  },
                  "sources": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              }
            }
          }
        ]
      }
    },
    "dialects": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "urn:thedndpub:schemas:core-rules:common:v1#/$defs/reference"
      }
    },
    "references": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "urn:thedndpub:schemas:core-rules:common:v1#/$defs/reference"
      }
    }
  }
}

=== Kloapte/the-dnd-pub-data/datasets/step-2/core-rules/v1/language/phb-dwarvish.json
{
  "id": "language:phb:dwarvish",
  "name": "Dwarvish",
  "sourceMetadata": {
    "source": "PHB",
    "page": 123,
    "flags": {
      "srd": true,
      "basicRules": true
    },
    "citations": [
      {
        "source": "PHB",
        "page": 18
      }
    ],
    "reprintedAs": [
      {
        "targetType": "language",
        "id": "language:xphb:dwarvish"
      }
    ]
  },
  "category": "standard",
  "script": "Dwarvish",
  "typicalSpeakers": [
    {
      "filter": {
        "targetType": "creature",
        "creatureTypes": [
          "humanoid"
        ],
        "tags": [
          {
            "group": "any race",
            "value": "dwarf"
          }
        ]
      }
    }
  ]
}

=== Kloapte/the-dnd-pub-data/datasets/step-2/core-rules/v1/language/ggr-elvish.json
{
  "id": "language:ggr:elvish",
  "name": "Elvish",
  "sourceMetadata": {
    "source": "GGR",
    "page": 9
  },
  "category": "standard",
  "script": "Elvish",
  "typicalSpeakers": [
    {
      "filter": {
        "targetType": "creature",
        "creatureTypes": [
          "humanoid"
        ],
        "tags": [
          {
            "group": "any race",
            "value": "elf"
          }
        ],
        "sources": [
          "GGR"
        ]
      }
    }
  ]
}

=== Kloapte/the-dnd-pub-data/datasets/phase-5/step-2/core-rules/v1/language/phb-deep-speech.json
{
  "id": "language:phb:deep-speech",
  "name": "Deep Speech",
  "sourceMetadata": {
    "source": "PHB",
    "page": 123,
    "flags": {
      "srd": true,
      "basicRules": true
    },
    "reprintedAs": [
      {
        "targetType": "language",
        "id": "language:xphb:deep-speech"
      }
    ]
  },
  "category": "exotic"
}

=== Kloapte/the-dnd-pub-data/datasets/step-2/core-rules/v1/language/erlw-daelkyr.json
{
  "id": "language:erlw:daelkyr",
  "name": "Daelkyr",
  "sourceMetadata": {
    "source": "ERLW",
    "page": 6
  },
  "category": "exotic",
  "script": "Daelkyr",
  "typicalSpeakers": [
    {
      "filter": {
        "targetType": "creature",
        "creatureTypes": [
          "aberration"
        ],
        "sources": [
          "ERLW"
        ]
      }
    }
  ]
}

=== Kloapte/the-dnd-pub-data/datasets/phase-5/step-2/core-rules/v1/language/ggr-sylvan.json
{
  "id": "language:ggr:sylvan",
  "name": "Sylvan",
  "sourceMetadata": {
    "source": "GGR",
    "page": 9,
    "citations": [
      {
        "source": "GGR",
        "page": 15
      }
    ]
  },
  "category": "standard",
  "script": "Elvish",
  "typicalSpeakers": [
    {
      "targetType": "creature",
      "id": "creature:ggr:conclave-dryad"
    }
  ]
}

=== Kloapte/the-dnd-pub-data/datasets/step-2/core-rules/v1/language/erlw-draconic.json
{
  "id": "language:erlw:draconic",
  "name": "Draconic",
  "sourceMetadata": {
    "source": "ERLW",
    "page": 6
  },
  "category": "exotic",
  "script": "Draconic",
  "typicalSpeakers": [
    {
      "filter": {
        "targetType": "creature",
        "creatureTypes": [
          "dragon"
        ],
        "sources": [
          "ERLW"
        ]
      }
    },
    {
      "filter": {
        "targetType": "creature",
        "creatureTypes": [
          "humanoid"
        ],
        "tags": [
          {
            "group": "any race",
            "value": "dragonborn"
          }
        ],
        "sources": [
          "ERLW"
        ]
      }
    }
  ]
}

=== Kloapte/the-dnd-pub-data/datasets/phase-5/step-2/core-rules/v1/language/phb-undercommon.json
{
  "id": "language:phb:undercommon",
  "name": "Undercommon",
  "sourceMetadata": {
    "source": "PHB",
    "page": 123,
    "flags": {
      "srd": true,
      "basicRules": true
    },
    "reprintedAs": [
      {
        "targetType": "language",
        "id": "language:xphb:undercommon"
      }
    ]
  },
  "category": "exotic",
  "script": "Elvish"
}

=== Kloapte/the-dnd-pub-data/datasets/step-2/core-rules/v1/language/phb-sylvan.json
{
  "id": "language:phb:sylvan",
  "name": "Sylvan",
  "sourceMetadata": {
    "source": "PHB",
    "page": 123,
    "flags": {
      "srd": true,
      "basicRules": true
    },
    "reprintedAs": [
      {
        "targetType": "language",
        "id": "language:xphb:sylvan"
      }
    ]
  },
  "category": "exotic",
  "script": "Elvish",
  "typicalSpeakers": [
    {
      "filter": {
        "targetType": "creature",
        "creatureTypes": [
          "fey"
        ]
      }
    }
  ]
}
