=== Kloapte/the-dnd-pub-data/schemas/core-rules/v1/language.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:thedndpub:schemas:core-rules:language:v1",
  "title": "Language",
  "allOf": [
    {
      "$ref": "urn:thedndpub:schemas:core-rules:common:v1#/$defs/identity"
    }
  ],
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "name",
    "sourceMetadata"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^language:[a-z0-9]+(?:-[a-z0-9]+)*:[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "sourceMetadata": {
      "$ref": "urn:thedndpub:schemas:core-rules:common:v1#/$defs/sourceMetadata"
    },
    "category": {
      "enum": [
        "standard",
        "exotic",
        "rare",
        "secret"
      ]
    },
    "script": {
      "type": "string",
      "minLength": 1
    },
    "origin": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "urn:thedndpub:schemas:core-rules:common:v1#/$defs/reference"
      }
    },
    "typicalSpeakers": {
      "type": "array",
      "minItems": 1,
      "items": {
        "oneOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "targetType",
              "id"
            ],
            "properties": {
              "targetType": {
                "const": "creature"
              },
              "id": {
                "type": "string",
                "pattern": "^creature:[a-z0-9-]+:[a-z0-9-]+$"
              }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "filter"
            ],
            "properties": {
              "filter": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "targetType",
                  "creatureTypes"
                ],
                "properties": {
                  "targetType": {
                    "const": "creature"
                  },
                  "creatureTypes": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                      "enum": [
                        "aberration",
                        "beast",
                        "celestial",
                        "construct",
                        "dragon",
                        "elemental",
                        "fey",
                        "fiend",
                        "giant",
                        "humanoid",
                        "monstrosity",
                        "ooze",
                        "plant",
                        "undead"
                      ]
                    }
                  },
                  "tags": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "required": [
                        "group",
                        "value"
                      ],
                      "properties": {
                        "group": {
                          "type": "string",
                          "minLength": 1
                        },
                        "value": {
                          "type": "string",
                          "minLength": 1
                        }
                      }
                    }
                  },
                  "sources": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              }
            }
          }
        ]
      }
    },
    "dialects": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "urn:thedndpub:schemas:core-rules:common:v1#/$defs/reference"
      }
    },
    "references": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "urn:thedndpub:schemas:core-rules:common:v1#/$defs/reference"
      }
    }
  }
}

=== Kloapte/the-dnd-pub-data/datasets/phase-5/step-2/core-rules/v1/language/psi-draconic.json
{
  "id": "language:psi:draconic",
  "name": "Draconic",
  "sourceMetadata": {
    "source": "PSI",
    "page": 9
  },
  "typicalSpeakers": [
    {
      "filter": {
        "targetType": "creature",
        "creatureTypes": [
          "dragon"
        ],
        "sources": [
          "PSI"
        ]
      }
    }
  ]
}

=== Kloapte/the-dnd-pub-data/datasets/step-2/core-rules/v1/language/xmm-worg.json
{
  "id": "language:xmm:worg",
  "name": "Worg",
  "sourceMetadata": {
    "source": "XMM",
    "page": 335
  },
  "typicalSpeakers": [
    {
      "targetType": "creature",
      "id": "creature:xmm:dire-worg"
    },
    {
      "targetType": "creature",
      "id": "creature:xmm:worg"
    }
  ]
}

=== Kloapte/the-dnd-pub-data/datasets/phase-5/step-2/core-rules/v1/language/phb-celestial.json
{
  "id": "language:phb:celestial",
  "name": "Celestial",
  "sourceMetadata": {
    "source": "PHB",
    "page": 123,
    "flags": {
      "srd": true,
      "basicRules": true
    },
    "reprintedAs": [
      {
        "targetType": "language",
        "id": "language:xphb:celestial"
      }
    ]
  },
  "category": "exotic",
  "script": "Celestial",
  "typicalSpeakers": [
    {
      "filter": {
        "targetType": "creature",
        "creatureTypes": [
          "celestial"
        ]
      }
    }
  ]
}

=== Kloapte/the-dnd-pub-data/datasets/phase-5/step-2/core-rules/v1/language/skt-bothii.json
{
  "id": "language:skt:bothii",
  "name": "Bothii",
  "sourceMetadata": {
    "source": "SKT",
    "page": 86,
    "reprintedAs": [
      {
        "targetType": "language",
        "id": "language:frhof:bothii"
      }
    ]
  },
  "typicalSpeakers": [
    {
      "targetType": "creature",
      "id": "creature:skt:uthgardt-barbarian-leader"
    },
    {
      "targetType": "creature",
      "id": "creature:skt:uthgardt-shaman"
    }
  ]
}

=== Kloapte/the-dnd-pub-data/datasets/phase-5/step-2/core-rules/v1/language/mm-thri-kreen.json
{
  "id": "language:mm:thri-kreen",
  "name": "Thri-kreen",
  "sourceMetadata": {
    "source": "MM",
    "page": 288,
    "reprintedAs": [
      {
        "targetType": "language",
        "id": "language:xmm:thri-kreen"
      }
    ]
  },
  "typicalSpeakers": [
    {
      "targetType": "creature",
      "id": "creature:mm:thri-kreen"
    }
  ]
}

=== Kloapte/the-dnd-pub-data/datasets/step-2/core-rules/v1/language/mm-sahuagin.json
{
  "id": "language:mm:sahuagin",
  "name": "Sahuagin",
  "sourceMetadata": {
    "source": "MM",
    "page": 263,
    "reprintedAs": [
      {
        "targetType": "language",
        "id": "language:xmm:sahuagin"
      }
    ]
  },
  "typicalSpeakers": [
    {
      "targetType": "creature",
      "id": "creature:mm:sahuagin"
    },
    {
      "targetType": "creature",
      "id": "creature:mm:sahuagin-priestess"
    },
    {
      "targetType": "creature",
      "id": "creature:mm:sahuagin-baron"
    }
  ]
}

=== Kloapte/the-dnd-pub-data/datasets/step-2/core-rules/v1/rule/dmg-milestones.json
{
  "id": "rule:dmg:milestones",
  "name": "Milestones",
  "sourceMetadata": {
    "source": "DMG",
    "page": 261
  },
  "references": [
    {
      "targetType": "rule",
      "id": "rule:xphb:experience-points",
      "relationship": "milestone-xp-award"
    },
    {
      "targetType": "rule",
      "id": "rule:xphb:encounter",
      "relationship": "milestone-xp-equivalent-encounter-difficulty"
    },
    {
      "targetType": "rule",
      "id": "rule:xphb:short-rest",
      "relationship": "optional-milestone-reward"
    },
    {
      "targetType": "rule",
      "id": "rule:xphb:hit-point-dice",
      "relationship": "optional-milestone-recovery-reward"
    }
  ]
}

=== Kloapte/the-dnd-pub-data/datasets/phase-5/step-2/core-rules/v1/language/mm-slaad.json
{
  "id": "language:mm:slaad",
  "name": "Slaad",
  "sourceMetadata": {
    "source": "MM",
    "page": 276,
    "reprintedAs": [
      {
        "targetType": "language",
        "id": "language:xmm:slaad"
      }
    ]
  },
  "typicalSpeakers": [
    {
      "targetType": "creature",
      "id": "creature:mm:slaad-tadpole"
    },
    {
      "targetType": "creature",
      "id": "creature:mm:red-slaad"
    },
    {
      "targetType": "creature",
      "id": "creature:mm:blue-slaad"
    },
    {
      "targetType": "creature",
      "id": "creature:mm:green-slaad"
    },
    {
      "targetType": "creature",
      "id": "creature:mm:gray-slaad"
    },
    {
      "targetType": "creature",
      "id": "creature:mm:death-slaad"
    }
  ]
}
